authors:
  mars:
    name: Jason Mars
    description: Creator of Jac, Enjoyer of beautiful tech, The ninja professor.
    avatar: https://avatars.githubusercontent.com/u/8206008?v=4
  malitha:
    name: Malitha
    description: Contributor
    avatar: https://avatars.githubusercontent.com/u/110366097?v=4
